# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Types',
            new_name='Type',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
